### PR TITLE
Added API_BASE environment variable

### PR DESCRIPTION
**Pull request by mikim83**
Useful for EU users.

### CODE REVIEW

**Comment by xbglowx** [comment]
Hi @mikim83,

Sorry for the late reply. For some reason I didn't get notified when this PR was created. Taking a look now.

**Comment by xbglowx** [comment]
@mikim83 LGTM with the exception of formatting. Can you please run `go fmt .`, amend the commit, and then update this PR?

**Comment by missionlane-atlantis** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs

**Comment by missionlane-atlantis** [comment]
Atlantis commands can't be run on fork pull requests. To enable, set --allow-fork-prs

**Comment by mikim83** [comment]
Hi there! Did the ```go fmt .``` part.
Thanks for you work!

**Comment by mikim83** [comment]
I'm such an idiot.. sorry ... xD

**Comment by xbglowx** [comment]
I will cut a new release shortly. Thanks for your contribution!

**Pull request merged**
